server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kaiburr
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
logging:
  level:
    root: info
